<a href="https://colab.research.google.com/github/2303A51801/Datascience-3-2/blob/main/Datascience03(7_8_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import numpy as np
import pandas as pd


In [ ]:
marks = np.array([85, 90, 78, 92])
print("Student Marks Array:\n", marks)

Student Marks Array:
 [85 90 78 92]


In [ ]:
# Step 2: Calculate average, min, and max marks per student
avg_marks = np.mean(marks)
min_marks = np.min(marks)
max_marks = np.max(marks)

In [ ]:

print("\nAverage Marks per Student:", avg_marks)
print("Minimum Marks per Student:", min_marks)
print("Maximum Marks per Student:", max_marks)


Average Marks per Student: 86.25
Minimum Marks per Student: 78
Maximum Marks per Student: 92


In [ ]:
sliced_marks = marks[1:4]
print("\nMarks of Student 2 to 4:\n", sliced_marks)


Marks of Student 2 to 4:
 [90 78 92]


In [ ]:
above_80 = marks[marks > 80]
print("\nStudents with any marks > 80:\n", above_80)


Students with any marks > 80:
 [85 90 92]


In [ ]:
subject_wise = marks.T
print("\nSubject-wise Performance:\n", subject_wise)


Subject-wise Performance:
 [85 90 78 92]


In [ ]:
print("\nSubject-wise Average Marks:", avg_marks)
print("Subject-wise Minimum Marks:", min_marks)
print("Subject-wise Maximum Marks:", max_marks)


Subject-wise Average Marks: 86.25
Subject-wise Minimum Marks: 78
Subject-wise Maximum Marks: 92
