<a href="https://colab.research.google.com/github/2303A51801/Datascience-3-2/blob/main/LAB3_DS_22_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
np.random.seed(10)  # for reproducibility
scores = np.random.randint(50, 100, size=(4, 4))  # Test scores between 50-100
print("Test Scores (4x4):\n", scores)


Test Scores (4x4):
 [[59 86 65 50]
 [99 78 75 79]
 [98 79 99 58]
 [59 50 92 90]]


In [5]:
row_mean = np.mean(scores, axis=1)
col_mean = np.mean(scores, axis=0)
print("\nRow-wise Mean:", row_mean)
print("Column-wise Mean:", col_mean)



Row-wise Mean: [65.   82.75 83.5  72.75]
Column-wise Mean: [78.75 73.25 82.75 69.25]


In [6]:
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation:", std_dev)
print("Variance:", variance)



Standard Deviation: 16.75559608011604
Variance: 280.75


In [7]:
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nGlobal Max:", global_max, "at index", max_index)
print("Global Min:", global_min, "at index", min_index)




Global Max: 99 at index (np.int64(1), np.int64(0))
Global Min: 50 at index (np.int64(0), np.int64(3))


In [8]:

print("\n--- Summary ---")
print(f"Row-wise Mean Scores: {row_mean}")
print(f"Column-wise Mean Scores: {col_mean}")
print(f"Overall Standard Deviation: {std_dev:.2f}")
print(f"Overall Variance: {variance:.2f}")
print(f"Highest Score: {global_max} at {max_index}")
print(f"Lowest Score: {global_min} at {min_index}")


--- Summary ---
Row-wise Mean Scores: [65.   82.75 83.5  72.75]
Column-wise Mean Scores: [78.75 73.25 82.75 69.25]
Overall Standard Deviation: 16.76
Overall Variance: 280.75
Highest Score: 99 at (np.int64(1), np.int64(0))
Lowest Score: 50 at (np.int64(0), np.int64(3))
